# Generated by Django 5.0 on 2024-06-23 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceType',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('attendance_name', models.CharField(blank=True, default='', max_length=255, verbose_name='勤務タイプ名')),
                ('sort_order', models.PositiveSmallIntegerField(verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person_in_charge', models.CharField(max_length=45, verbose_name='担当者名')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': 'クライアント',
                'verbose_name_plural': 'クライアント',
            },
        ),
        migrations.CreateModel(
            name='CommonHoliday',
            fields=[
                ('date_day', models.DateField(primary_key=True, serialize=False, unique=True, verbose_name='日付')),
                ('name', models.CharField(max_length=32, verbose_name='祝日名')),
            ],
            options={
                'verbose_name': '共通祝日',
                'verbose_name_plural': '共通祝日',
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('contract_type_name', models.CharField(blank=True, default='', max_length=255, verbose_name='契約タイプ名')),
                ('sort_order', models.PositiveSmallIntegerField(verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('main_name', models.CharField(max_length=255, verbose_name='メイン名')),
                ('sub_name', models.CharField(max_length=255, verbose_name='サブ名')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='備考')),
                ('started_on', models.DateField(verbose_name='開始日')),
                ('ended_on', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': 'プロジェクト',
                'verbose_name_plural': 'プロジェクト',
            },
        ),
        migrations.CreateModel(
            name='UserOnProjectMonth',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjusted_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='調整時間')),
                ('private_note', models.CharField(blank=True, default='', max_length=255, verbose_name='個人メモ')),
                ('public_note', models.CharField(blank=True, default='', max_length=255, verbose_name='公開メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': 'ユーザプロジェクト月',
                'verbose_name_plural': 'ユーザプロジェクト月',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='単価')),
                ('lower_hours_a_month', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='下限時間')),
                ('upper_hours_a_month', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='上限時間')),
                ('latest_work_started_at', models.TimeField(verbose_name='規定の開始時刻')),
                ('earliest_work_ended_at', models.TimeField(verbose_name='規定の終了時刻')),
                ('work_hours_a_day', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='所定勤務時間')),
                ('rest_hours_a_day', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='所定休憩時間')),
                ('started_on', models.DateField(verbose_name='契約開始日')),
                ('ended_on', models.DateField(blank=True, null=True, verbose_name='契約終了日')),
                ('contract_name', models.CharField(default='', max_length=255, verbose_name='契約名')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.contracttype', verbose_name='契約形態')),
            ],
            options={
                'verbose_name': '契約',
                'verbose_name_plural': '契約',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=30, unique=True, verbose_name='uid')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post', verbose_name='サムネイル')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '投稿',
                'verbose_name_plural': '投稿',
            },
        ),
        migrations.CreateModel(
            name='UserOnProject',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.client', verbose_name='クライアント')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.contract', verbose_name='契約')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project', verbose_name='プロジェクト')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザプロジェクト',
                'verbose_name_plural': 'ユーザプロジェクト',
            },
        ),
        migrations.CreateModel(
            name='UserOnProjectIndex',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_year_month', models.DateField(verbose_name='年月')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('user_on_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indexes', to='app.useronproject', verbose_name='ユーザプロジェクト')),
                ('user_on_project_month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.useronprojectmonth', verbose_name='ユーザプロジェクト月')),
            ],
            options={
                'verbose_name': 'ユーザプロジェクトインデックス',
                'verbose_name_plural': 'ユーザプロジェクトインデックス',
            },
        ),
        migrations.CreateModel(
            name='UserOnProjectDay',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_index', models.PositiveSmallIntegerField(verbose_name='日にちインデックス')),
                ('date_day', models.DateField(verbose_name='日付')),
                ('should_work_day', models.BooleanField(default=True, verbose_name='稼働日')),
                ('work_started_at', models.TimeField(blank=True, default=None, null=True, verbose_name='開始時刻')),
                ('work_ended_at', models.TimeField(blank=True, default=None, null=True, verbose_name='終了時刻')),
                ('rest_hours', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True, verbose_name='休憩時間')),
                ('private_note', models.CharField(blank=True, default='', max_length=255, verbose_name='個人メモ')),
                ('public_note', models.CharField(blank=True, default='', max_length=255, verbose_name='公開メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='days', to='app.useronprojectmonth', verbose_name='ユーザプロジェクト月')),
            ],
            options={
                'verbose_name': 'ユーザプロジェクト日',
                'verbose_name_plural': 'ユーザプロジェクト日',
            },
        ),
        migrations.CreateModel(
            name='UserOnProjectTime',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_index', models.PositiveSmallIntegerField(verbose_name='時間インデックス')),
                ('work_started_at', models.TimeField(verbose_name='開始時刻')),
                ('work_ended_at', models.TimeField(verbose_name='終了時刻')),
                ('rest_started_at', models.TimeField(verbose_name='休憩開始時刻')),
                ('rest_ended_at', models.TimeField(verbose_name='休憩終了時刻')),
                ('private_note', models.CharField(blank=True, default='', max_length=255, verbose_name='個人メモ')),
                ('public_note', models.CharField(blank=True, default='', max_length=255, verbose_name='公開メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='times', to='app.useronprojectday', verbose_name='ユーザプロジェクト月')),
            ],
            options={
                'verbose_name': 'ユーザプロジェクト時間',
                'verbose_name_plural': 'ユーザプロジェクト時間',
            },
        ),
        migrations.CreateModel(
            name='UserSpecialAttendance',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='uid')),
                ('date_day', models.DateField(verbose_name='日付')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('attendance_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='app.attendancetype', verbose_name='勤務タイプ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザ特別勤務',
                'verbose_name_plural': 'ユーザ特別勤務',
            },
        ),
        migrations.AddConstraint(
            model_name='useronprojectindex',
            constraint=models.UniqueConstraint(fields=('user_on_project', 'date_year_month'), name='unique_user_project_index'),
        ),
        migrations.AddConstraint(
            model_name='useronprojectday',
            constraint=models.UniqueConstraint(fields=('month', 'day_index'), name='unique_user_project_day'),
        ),
        migrations.AddConstraint(
            model_name='useronprojecttime',
            constraint=models.UniqueConstraint(fields=('day', 'time_index'), name='unique_user_project_time'),
        ),
        migrations.AddConstraint(
            model_name='userspecialattendance',
            constraint=models.UniqueConstraint(fields=('user', 'date_day'), name='unique_user_special_attendance'),
        ),
    ]
