# Generated by Django 5.0 on 2024-06-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useronprojecttime',
            name='rest_ended_at',
            field=models.TimeField(blank=True, null=True, verbose_name='休憩終了時刻'),
        ),
        migrations.AlterField(
            model_name='useronprojecttime',
            name='rest_started_at',
            field=models.TimeField(blank=True, null=True, verbose_name='休憩開始時刻'),
        ),
    ]
