# Generated by Django 5.0 on 2024-05-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_attendancetype_client_commonholiday_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('contract_type_name', models.CharField(blank=True, default='', max_length=255, verbose_name='契約タイプ名')),
                ('sort_order', models.PositiveSmallIntegerField(verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
    ]
