# Generated by Django 5.0 on 2024-05-19 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_attendancetype_client_commonholiday_contracttype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': '契約', 'verbose_name_plural': '契約'},
        ),
    ]
