# Generated by Django 5.0 on 2024-05-10 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contracttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontract',
            name='contract_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.contracttype', verbose_name='契約形態'),
        ),
    ]
